pipeline:
  name: reactunit
  identifier: reactunit
  projectIdentifier: Shell
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.fmazlabsgit
        repoName: reactunit
        build: <+input>
  stages:
    - stage:
        name: appbuild
        identifier: appbuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          serviceDependencies:
            - identifier: DinD
              name: DinD
              type: Service
              description: DinD
              spec:
                connectorRef: account.harnessImage
                image: docker:dind
          execution:
            steps:
              - step:
                  type: Run
                  name: YarnInstall
                  identifier: YarnInstall
                  spec:
                    shell: Sh
                    command: |-
                      yarn install
                      yarn build 
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
