pipeline:
  name: reactunit
  identifier: reactunit
  projectIdentifier: Shell
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.fmazlabsgit
        repoName: reactunit
        build: <+input>
  stages:
    - stage:
        name: appbuild
        identifier: appbuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          serviceDependencies:
            - identifier: DinD
              name: DinD
              type: Service
              description: DinD
              spec:
                connectorRef: account.harnessImage
                image: docker:dind
          execution:
            steps:
              - step:
                  type: Run
                  name: YarnInstall
                  identifier: YarnInstall
                  spec:
                    shell: Sh
                    command: |-
                      yarn install
                      yarn build 
                  description: Yarn Install and Build
              - step:
                  type: Run
                  name: Yarn Add
                  identifier: Yarn_Add
                  spec:
                    shell: Sh
                    command: |-
                      import '../node_modules/bootstrap/dist/css/bootstrap.min.css'
                      yarn create react-app my-app
                      yarn add enzyme enzyme-adapter-react-16 --dev
                      yarn add react-test-renderer --dev
                      yarn add bootstrap
                  description: Yarn Add
              - step:
                  type: Run
                  name: Test Yarn
                  identifier: Test_Yarn
                  spec:
                    shell: Sh
                    command: yarn test
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                  description: Yarn Test
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
